### PR TITLE
Remove Conversation pipeline utils

### PR DESCRIPTION
**Pull request by ed-berry**
*Issue #129*
Remove support for the deprecated Conversation pipeline that has been removed from transformers as of v4.42.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Review by philschmid — APPROVED** [review]
Thank you for removing the pipeline

**Comment by philschmid** [comment]
@ed-berry can you run `make style` to make sure the CI passes?

**Comment by ed-berry** [comment]
Hey @philschmid, looks like it was an unused import of `pipeline` in the tests. I've now removed this

**Comment by joann-alvarez** [comment]
Hello @philschmid! Is there someone else who needs to be tagged to approve for merging?

**Comment by joann-alvarez** [comment]
Thank you @ed-berry @philschmid!

**Pull request merged**
